name: Nidacon
favicon: null
layout_spectrum: 0.24656
typography_spectrum: 0.56932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9600fa'
    - '#b2b2b2'
    - '#c36efc'
    - '#ab32fa'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
