typography_spectrum: 0.56932
color:
  brandColors:
    - '#ffffff'
    - '#4092cf'
    - '#a2057e'
    - '#c641c0'
    - '#dd88c3'
  brandStrength: 0.125
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26031
analytics:
  google: null
  facebook: null
  twitter: null
name: Nidacon
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Products
    id: 51f2e885-bfa0-442a-94c0-61e92160bb75
    type: content
favicon: null
title: PureSperm
purpose: []
