name: Nidacon
favicon: null
layout_spectrum: 0.7572
typography_spectrum: 0.56932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4092cf'
    - '#a2057e'
    - '#c641c0'
    - '#dd88c3'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
